### ISSUE TITLE
ModuleNotFoundError: No module named 'metrics'

### ISSUE THREAD

**Issue by robmarkcole** [JAVI897/ML-Metrics#1]
Hi
on running the app:
```
ModuleNotFoundError: No module named 'metrics'
File "/usr/local/lib/python3.7/site-packages/streamlit/ScriptRunner.py", line 306, in _run_script exec(code, module.__dict__)
File "/var/folders/th/p79ctr092t9c_795pyl79n6c0000gn/T/tmpllxt6_gj", line 2, in <module> import metrics
```
I have 
* streamlit==0.48.1
* plotly==4.2.1
numpy, pandas

**Comment by JAVI897** [comment]
Hi Robin,
Could you give me more details about the error, please?

Thanks!
Javi

**Comment by JAVI897** [comment]
Hi, I've updated the readme. This is how you should run the app now:

![Captura de pantalla (517)](https://user-images.githubusercontent.com/13927971/67380676-fcf94f80-f58a-11e9-87f7-9d6362a91366.png)

**Comment by robmarkcole** [comment]
OK I tried on my work machine, and the error was same but included extra info - I was missing plotly, sorry!
